# Makefile.rule
# defines the rule, which consists of target, prerequisite and recipe.

# compatibility for old Makefile.template
TEXENGINEOPT ?= -pdf
$(TARGET.pdf): %.pdf: %.tex
	$(LATEXMK) $(TEXENGINEOPT) -f -interaction=nonstopmode '$(firstword $<)'

pdfclean: backup
	$(LATEXMK) $(TEXENGINEOPT) -C '$(TARGET.base)'

CLEAN += pdfclean
ALLCLEAN += pdfclean


