# docker-compose.yml
version: '3.4'
services:
    latexml_edge:
        build:
            context: docker/LaTeXML_edge
            dockerfile: ../LaTeXML-Dockerfile_edge
            #dockerfile: release/docker/Dockerfile
            target: latexml_base_edge
            args:
                - WITH_TEXLIVE=yes
                - WITH_TESTS=no
        command: 'echo "OK, that this container exits."'

    latexml_dmake_edge:
        build:
            context: docker/latexml_dmake_edge
            dockerfile: Dockerfile
            target: latexml_dmake_edge
            args:
                # Sometimes a job (e.g. latexml) may run endlessly, limit
                # the amount of time a job can run.
                TIMEOUT_SECONDS: 1200

        environment:
            DOCKERIZED: 1
        networks:
            texmlbus_net:
                aliases:
                    - worker_edge
        volumes:
            - ./volume/articles:/srv/texmlbus/articles
            - ./volume/src:/srv/texmlbus/src
            - optrun:/opt/run


networks:
    texmlbus_net:
volumes:
    # shared by latexml-dmake and texmlbus
    optrun:

