#!/bin/bash
#
# Heinrich Stamerjohanns, 2020
#
SCRIPTDIR=$(dirname "$(readlink -f "$0")")

if [[ $OS = "Windows_NT" ]]
then
    WINPTY="winpty"
else
    WINPTY=""
fi
. ${SCRIPTDIR}/is-dc-v2.sh

is_dc_v2
if [[ "$?" == "1" ]]; then
    CONTAINER="texmlbus-mariadb-1"
else
    CONTAINER="texmlbus_mariadb_1"
fi
#
# use double slashes so winpty does not convert paths
#
$WINPTY docker exec -it ${CONTAINER} //bin/bash
