#!/bin/bash
#
# Heinrich Stamerjohanns, 2020
#
SCRIPTDIR=$(dirname "$(readlink -f "$0")")

if [[ $OS = "Windows_NT" ]]
then
    WINPTY="winpty"
else
    WINPTY=""
fi

CONTAINER="mariadb"

#
# use double slashes so winpty does not convert paths
#
$WINPTY docker-compose exec ${CONTAINER} //bin/bash
